export const TEST = 'TEST'
//ARTICLES
export const CLEAR_ARTICLES = 'CLEAR_ARTICLES'
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY'
export const SET_USER_ARTICLES = 'SET_USER_ARTICLES'
export const SET_SEND_ARTICLE = 'SET_SEND_ARTICLE'
export const ARTICLE_ERROR = 'ARTICLE_ERROR'
export const ARTICLE_SEARCH = 'ARTICLE_SEARCH'

//USER
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const AUTO_AUTH_SUCCESS = 'AUTO_AUTH_SUCCESS'

// PROFILE
export const SET_PROFILE = 'SET_PROFILE'
export const SET_PROFLE_LOADING = 'SET_PROFLE_LOADING'
export const START_PROFILE = 'START_PROFILE'
export const FOLLOW = 'FOLLOW'
export const UNFOLLOW = 'UNFOLLOW'
