export const TEST = 'TEST'
//ARTICLES
export const CLEAR_ARTICLES = 'CLEAR_ARTICLES'
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY'
export const SET_MY_ARTICLES = 'SET_MY_ARTICLES'

//USER
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const AUTO_AUTH_SUCCESS = 'AUTO_AUTH_SUCCESS'


